version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  node:
    image: node:18-alpine
    volumes:
      - .:/app:ro  # Mount project directory in read-only mode
    entrypoint: [ "npm", "install" ]
    command: [ "npm", "run", "watch" ]  # Assuming a "watch" script in package.json
volumes:
  postgres_data: