[tool.poetry]
name = "OtakuSearch"
version = "0.1.0"
description = ""
authors = ["David Sarrat González <113605621+davidsarratgonzalez@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0.2"
pre-commit = "^3.6.2"
django-tailwind = "^3.8.0"
django-browser-reload = "^1.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
